#!/bin/bash

touch $HOME/.hamonikr/${0##*/}.log
echo "$(date +%Y-%m-%d_%H:%M) : ${0##*/} $1 running." | tee $HOME/.hamonikr/${0##*/}.log

if [ ! -f "/home/$USER/.hamonikr/updated-dconf" ] ; then

    # 패널 상단 배치
    # gsettings set org.cinnamon panels-enabled "['1:0:top']"
    
    # 패널 애플릿 배치
    gsettings set org.cinnamon enabled-applets "['panel1:left:0:menu@cinnamon.org:0', 'panel1:right:11:show-desktop@cinnamon.org:14', 'panel1:left:2:grouped-window-list@cinnamon.org:2', 'panel1:right:1:systray@cinnamon.org:3', 'panel1:right:2:notifications@cinnamon.org:4', 'panel1:right:3:printers@cinnamon.org:5', 'panel1:right:4:removable-drives@cinnamon.org:6', 'panel1:right:5:keyboard@cinnamon.org:7', 'panel1:right:6:bluetooth@cinnamon.org:8', 'panel1:right:7:network@cinnamon.org:9', 'panel1:right:8:sound@cinnamon.org:10', 'panel1:right:9:power@cinnamon.org:11', 'panel1:right:10:calendar@cinnamon.org:12', 'panel1:right:0:xrandr@cinnamon.org:13']"
    
    # 시스템 폰트 설정 시스템 설정 > 기본 글꼴
    gsettings set org.cinnamon.desktop.interface font-name "나눔스퀘어라운드 Regular 10"
    # 시스템 설정 > 바탕화면 글꼴
    gsettings set org.nemo.desktop font "나눔스퀘어라운드 Regular 10"
    # 시스템 설정 > 문서 글꼴
    gsettings set org.gnome.desktop.interface document-font-name "나눔스퀘어라운드 Regular 10"
    # 시스템 설정 > 고정폭 글꼴
    gsettings set org.gnome.desktop.interface monospace-font-name "나눔스퀘어라운드 Regular 10"
    # 시스템 설정 > 창제목 글꼴
    gsettings set org.cinnamon.desktop.wm.preferences titlebar-font "나눔스퀘어라운드 Bold 10"
    
    # gnome-terminal 설정
    if [ -f "/home/$USER/.hamonikr/hamonikr-jin-terminal.dconf" ] ; then
        dconf load /org/gnome/terminal/legacy/profiles:/:`gsettings list-recursively org.gnome.Terminal.ProfilesList | grep default | cut -d' ' -f3 | tr -d "'"`/ < /home/$USER/.hamonikr/hamonikr-jin-terminal.dconf
    fi

    # nimf 입력기 설정
    if command -v nimf &> /dev/null
    then
        im-config -n nimf
    fi

    # 단축키
    if command -v shutter &> /dev/null ; then
        if ! command -v fsearch &> /dev/null ; then
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Primary><Shift>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'shutter -s'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name '특정영역 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ binding "['<Primary><Alt>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ command 'shutter -w'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ name '선택한 윈도우 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings custom-list "['custom0','custom1']"
        else
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Primary><ALT><Shift>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'shutter -s'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name '특정영역 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ binding "['<Primary><Alt>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ command 'shutter -w'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ name '선택한 윈도우 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ binding "['<Primary><Shift>f']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ command 'fsearch'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ name '데스크탑 검색'
            gsettings set org.cinnamon.desktop.keybindings custom-list "['custom0','custom1','custom2']"
        fi
    fi

    touch /home/$USER/.hamonikr/updated-dconf
fi