#!/bin/sh

set -e

case "$1" in
    configure|triggered)
        if which systemctl >/dev/null 2>&1
        then
            echo "Reloading systemd"
            systemctl disable ubuntu-system-adjustments
            systemctl enable hamonikr-system-settings.service
            systemctl daemon-reload || true
        fi

        /usr/bin/hamonikr-system-start || true
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0


