#!/usr/bin/python3
import datetime
import subprocess


try:
    # Log current datetime
    now = str(datetime.datetime.now())
    with open("/var/log/hamonikr-system-adjustments-start.log", "w") as f:
        f.write(now)

    # Adjust Grub title
    subprocess.call(["/usr/share/hamonikr-system-adjustments/systemd/adjust-grub-title"])

except:
    pass

